name: GitHub Actions Demo
run-name: ${{ github.actor }} está corriendo los tests unitarios usando GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Correr tests unitarios
        run: |
            python unit_tests.py
        working-directory: tp