name: GitHub Actions Demo
run-name: ${{ github.actor }} está corriendo los tests unitarios usando GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "tp/requirements.txt"

      - name: Install Angular CLI and dependencies
        run: |
          cd frontend
          npm install -g @angular/cli
          npm install

      - name: Download ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64
      
      - name: Start frontend
        run: |
          sudo apt --fix-broken install
          sudo apt-get update && sudo apt-get install -y curl
          cd frontend
          ng serve --host 0.0.0.0 &
          for attempt in {1..40}; do sleep 1; if curl -s http://localhost:4200 >/dev/null; then echo ready; break; fi; echo waiting...; done 
      
      - name: Start backend
        run: |
          cd tp
          uvicorn main:app --reload &
          for attempt in {1..20}; do sleep 1; if curl -s http://localhost:8000 >/dev/null; then echo ready; break; fi; echo waiting...; done 

      - name: Run unit tests with coverage
        run: |
          cd ./tp
          coverage run unit_tests.py
          coverage report
      
      - name: Run Acceptance tests
        run: |
          cd tp
          behave -f allure_behave.formatter:AllureFormatter -o at_results ./features
          allure generate at_results -o allure-report
