name: GitHub Actions Demo
run-name: ${{ github.actor }} está corriendo los tests unitarios usando GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "tp/requirements.txt"

      - name: Run unit tests
        run: |
          cd ./tp
          python unit_tests.py

      - name: Run unit tests coverage
        run: |
          cd ./tp
          coverage run unit_tests.py